<?php

namespace Estokin\PanelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	
	/**
	 * Gets categories.
	 *
	 *
	 * @return Estokin\PanelBundle\Entity\Category
	 */
	public function getCategoriesTree()
	{
		$q = $this->createQueryBuilder('c')
		->where('c.level = 0');
		return $q->getQuery()->getResult();
	}

}