<?php

namespace Estokin\PanelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
	
	/**
	 * Gets total items by user.
	 *
	 * @param string $shop
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForList($shop)
	{
		$q = $this->createQueryBuilder('p')
		->where('p.shop = :shop', 'p.state != :state')
		->setParameter('shop', $shop)
		->setParameter('state', 'STATE_DEAD');		
		return $q->getQuery()->getResult(); 
	}
	/**
	 * Gets total list items.
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForListA()
	{
		$q = $this->createQueryBuilder('p')
		->where('p.state != :state')
		->setParameter('state', 'STATE_DEAD');		
		return $q->getQuery()->getResult(); 
	}	
	/**
	 * Gets total items num by user.
	 *
	 * @param string $shop
	 *
	 * @return integer
	 */
	public function getNumTotal($shop)
	{
		$q = $this->createQueryBuilder('p')
		->select('count(p.id)')
		->where('p.shop = :shop', 'p.state != :state')
		->setParameter('shop', $shop)
		->setParameter('state', 'STATE_DEAD');		
		return current($q->getQuery()->getSingleResult()); 
	}
	/**
	 * Gets total items num.
	 *
	 * @return integer
	 */
	public function getNumTotalA()
	{
		$q = $this->createQueryBuilder('p')
		->select('count(p.id)')
		->where('p.state != :state')
		->setParameter('state', 'STATE_DEAD');		
		return current($q->getQuery()->getSingleResult()); 
	}		
	
	/**
	 * Gets local items by user.
	 *
	 * @param string $shop
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForLocal($shop)
	{
		$q = $this->createQueryBuilder('i')
		->Where('i.shop = :shop')
		->innerJoin('i.product', 'p', 'WITH', 'p.state = :state1 OR p.state = :state2')
		->setParameter('shop', $shop)
		->setParameter('state1', 'STATE_RAW')
		->setParameter('state2', 'STATE_VALID')
		->orderBy('i.date_add', 'DESC');
		return $q->getQuery()->getResult();
	}
	
	/**
	 * Gets local items.
	 *
	 * @param string $shop
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForLocalA()
	{
		$q = $this->createQueryBuilder('i')
		->innerJoin('i.product', 'p', 'WITH', 'p.state = :state1 OR p.state = :state2')
		->setParameter('state1', 'STATE_RAW')
		->setParameter('state2', 'STATE_VALID')
		->orderBy('i.date_add', 'DESC');
		return $q->getQuery()->getResult();
	}
	
	/**
	 * Gets online items by user.
	 *
	 * @param string $shop
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForStock($shop)
	{
		$q = $this->createQueryBuilder('i')
		->Where('i.shop = :shop')
		->innerJoin('i.product', 'p', 'WITH', 'p.state = :state1')
		->setParameter('shop', $shop)
		->setParameter('state1', 'STATE_ONLINE')
		->orderBy('i.date_add', 'DESC');
		return $q->getQuery()->getResult();
	}
	/**
	 * Gets online items.
	 *
	 * @param string $shop
	 *
	 * @return Estokin\PanelBundle\Entity\Item
	 */
	public function getForStockA()
	{
		$q = $this->createQueryBuilder('i')
		->innerJoin('i.product', 'p', 'WITH', 'p.state = :state1')
		->setParameter('state1', 'STATE_ONLINE')
		->orderBy('i.date_add', 'DESC');
		return $q->getQuery()->getResult();
	}
}