security:
    encoders:
        Estokin\PanelBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Estokin\PanelBundle\Entity\User, property: username }

        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false
            
        web_service:
            pattern: ^/wservice/pshook$
            anonymous: ~
            form_login: false
                    
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            http_basic:
                realm: "Secured Area"

                

    access_control:
        #- { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/wservice/pshook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/item/admin, roles: ROLE_ADMIN }
        - { path: ^/item, roles: ROLE_USER }
        - { path: ^/shop/profile, roles: ROLE_USER }
        - { path: ^/shop/update, roles: ROLE_USER }
        - { path: ^/shop, roles: ROLE_ADMIN }
        - { path: ^/user/chpassword, roles: ROLE_USER }
        - { path: ^/user/updatepassword, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
